version: '3.1'

services:
  nginx:
    container_name: ${CONTAINER_PREFIX}_nginx
    image: nginx
    ports:
      - "${HTTP_PORT}:80"
    volumes:
      - ./../public:/usr/share/nginx/html
    environment:
      - "NGINX_HOST=${HOST}"
